### ISSUE TITLE
minecraft crash when i use JARM 1,12.2.16

### ISSUE THREAD

**Issue by andrewq99** [NicosaurusRex99/JARMGit#8] opened 2018-06-19 16:59 UTC
minecraft crash when i use JARM 1,12.2.16 but when i use JARM 1,12.2.15 i am fine and minecraft dose not crash

**Comment by andrewq99** [comment] 2018-06-19 17:09
it crash an dose this. The game crashed whilst exception in server tick loop Error: java.lang.IllegalArgumentException: bound must be positive

**Comment by andrewq99** [comment] 2018-06-19 17:10
her the crash report

**Comment by andrewq99** [comment] 2018-06-19 17:11
Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/19/18 5:16 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at naturix.jarm.world.ModWorldGeneration.generateOre(ModWorldGeneration.java:102)
	at naturix.jarm.world.ModWorldGeneration.generateOverworld(ModWorldGeneration.java:168)
	at naturix.jarm.world.ModWorldGeneration.generate(ModWorldGeneration.java:29)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1018)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319072776 bytes (304 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 89
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 Optifine OptiFine_1.12.2_HD_U_D3 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version       | Source                                 | Signature                                |
	|:------- |:------------------- |:------------- |:-------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft           | 1.12.2        | minecraft.jar                          | None                                     |
	| UCHIJAA | mcp                 | 9.42          | minecraft.jar                          | None                                     |
	| UCHIJAA | FML                 | 8.0.99.99     | forge-1.12.2-14.23.4.2708.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge               | 14.23.4.2708  | forge-1.12.2-14.23.4.2708.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | basemetals          | 2.5.0-beta5   | BaseMetals-1.12-2.5.0-beta5.214.jar    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | baseminerals        | 2.5.0-beta5   | BaseMinerals-1.12-2.5.0-beta5.43.jar   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | basicmetals         | 0.0.1         | basicmetals-1.12-1.0.jar               | None                                     |
	| UCHIJAA | chameleon           | 1.12-4.1.3    | Chameleon-1.12-4.1.3.jar               | None                                     |
	| UCHIJAA | orespawn            | 3.3.0         | OreSpawn-1.12-3.3.0.136.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | densemetals         | 1.2.0         | DenseMetals-1.12-1.2.0.20.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | silentlib           | 2.3.1         | SilentLib-1.12.2-2.3.1-107.jar         | None                                     |
	| UCHIJAA | funores             | 1.5.7         | FunOres-1.12-1.5.7-118.jar             | None                                     |
	| UCHIJAA | hardcoreore         | 0.2.0         | hardcoreore-1.12.2-0.2.0.jar           | None                                     |
	| UCHIJAA | terracore           | 2.1.12        | TerraCore-1.12-2.1.12.jar              | None                                     |
	| UCHIJAA | ingotter            | 1.12-2.0.9    | Ingotter-1.12-2.0.9.jar                | None                                     |
	| UCHIJAA | jarm                | 1.12.2.16     | jarm-1.12.2.16.jar                     | None                                     |
	| UCHIJAA | jei                 | 4.9.1.175     | jei_1.12.2-4.9.1.175.jar               | None                                     |
	| UCHIJAA | lotsoores           | Alpha v1.2.01 | lotsores-1.12.2-alpha-v1.2.01.jar      | None                                     |
	| UCHIJAA | minepix             | 1.0           | Minepix_1.0.jar                        | None                                     |
	| UCHIJAA | modernmetals        | 2.5.0-beta5   | ModernMetals-1.12-2.5.0-beta5.120.jar  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAA | bop                 | 1.0           | MoreOres-1.0.1.jar                     | None                                     |
	| UCHIJAA | powerinventory      | 2.3.1         | OverpoweredInventory-1.12-2.3.1.jar    | None                                     |
	| UCHIJAA | simplecore          | 1.6.0.6       | simplecore-1.12.2-1.6.0.6.jar          | None                                     |
	| UCHIJAA | simpleores          | 1.11.1.9      | simpleores-1.12.2-1.11.1.9.jar         | None                                     |
	| UCHIJAA | storagedrawers      | 1.12-5.3.5    | StorageDrawers-1.12.2-5.3.6.jar        | None                                     |
	| UCHIJAA | superores           | 1.8.4_1.12    | superores-1.8.4_1.12.jar               | None                                     |
	| UCHIJAA | techores            | 1.1           | Tech+Ores+1.1+[1.12.2].jar             | None                                     |
	| UCHIJAA | theoneprobe         | 1.4.22        | theoneprobe-1.12-1.4.22.jar            | None                                     |
	| UCHIJAA | veinminer           | 0.38.2        | VeinMiner-1.12-0.38.2.647+b31535a.jar  | None                                     |
	| UCHIJAA | veinminermodsupport | 0.38.2        | VeinMiner-1.12-0.38.2.647+b31535a.jar  | None                                     |
	| UCHIJAA | xaerominimap        | 1.15.1.2      | Xaeros_Minimap_1.15.1.2_Forge_1.12.jar | None                                     |
	| UCHIJAA | zeiyocraft          | 0.8.4         | zeiyocraft-0.8.4.jar                   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4749
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by NicosaurusRex99** [comment] 2018-06-20 03:00
Can you post a copy of your config file it would be in documents>curse>minecraft>instances>(modpack name)>config>naturix>Just Another Ruby Mod!.
Im not sure why this issue occurs because [Line 168](https://github.com/NicosaurusRex99/JARMGit/blob/1.12.2/src/main/java/naturix/JARM/world/ModWorldGeneration.java#L168) is fine and returns a positive unless a negative value or 0 is input in the config.

**Comment by andrewq99** [comment] 2018-06-20 08:06
# Configuration file

##########################################################################################################
# armour
#--------------------------------------------------------------------------------------------------------#
# Armour values
##########################################################################################################

armour {
    # Damage reduction on the amethyst boots. [range: 1 ~ 1000000, default: 6]
    I:amethystBoot=6

    # Damage reduction on the amethyst chestplate. [range: 1 ~ 1000000, default: 10]
    I:amethystChest=10

    # Damage reduction on the amethyst helmet. [range: 1 ~ 1000000, default: 6]
    I:amethystHelm=6

    # Damage reduction on the amethyst leggings. [range: 1 ~ 1000000, default: 13]
    I:amethystLeg=13

    # Damage reduction on the emerald boots. [range: 1 ~ 1000000, default: 3]
    I:emeraldBoot=3

    # Damage reduction on the emerald chestplate. [range: 1 ~ 1000000, default: 7]
    I:emeraldChest=7

    # Damage reduction on the emerald helmet. [range: 1 ~ 1000000, default: 4]
    I:emeraldHelm=4

    # Damage reduction on the emerald leggings. [range: 1 ~ 1000000, default: 5]
    I:emeraldLeg=5

    # Damage reduction on the lapis boots. [range: 1 ~ 1000000, default: 2]
    I:lapisBoot=2

    # Damage reduction on the lapis chestplate. [range: 1 ~ 1000000, default: 5]
    I:lapisChest=5

    # Damage reduction on the lapis helmet. [range: 1 ~ 1000000, default: 2]
    I:lapisHelm=2

    # Damage reduction on the lapis leggings. [range: 1 ~ 1000000, default: 3]
    I:lapisLeg=3

    # Damage reduction on the prismarine helmet. [range: 1 ~ 1000000, default: 2]
    I:prismarineHelm=2

    # Damage reduction on the ruby boots. [range: 1 ~ 1000000, default: 5]
    I:rubyBoot=5

    # Damage reduction on the ruby chestplate. [range: 1 ~ 1000000, default: 9]
    I:rubyChest=9

    # Damage reduction on the ruby helmet. [range: 1 ~ 1000000, default: 5]
    I:rubyHelm=5

    # Damage reduction on the ruby leggings. [range: 1 ~ 1000000, default: 12]
    I:rubyLeg=12

    # Damage reduction on the shulker boots. [range: 1 ~ 1000000, default: 4]
    I:shulkerBoot=4

    # Damage reduction on the shulker chestplate. [range: 1 ~ 1000000, default: 8]
    I:shulkerChest=8

    # Damage reduction on the shulker helmet. [range: 1 ~ 1000000, default: 5]
    I:shulkerHelm=5

    # Damage reduction on the shulker leggings. [range: 1 ~ 1000000, default: 10]
    I:shulkerLeg=10
}


##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# General configuration
##########################################################################################################

general {
    # How long until the meteor can pull more stuff [range: 1 ~ 1000000, default: 4]
    I:MeteorCooldown=4

    # Meteor max pull [range: 1 ~ 1000000, default: 4]
    I:MeteorPull=4

    # Meteor pull speed [range: 1 ~ 1000000, default: 4]
    I:MeteorPullSpeed=4

    # Meteor pull range [range: 1 ~ 1000000, default: 4]
    I:MeteorRange=4

    # Set to false to disable ingot/gem blocks from being a beacon base [default: true]
    B:addBeaconBase=true

    # Disable to remove the ingame update notification [default: true]
    B:"update alerts"=true
}


##########################################################################################################
# misc
#--------------------------------------------------------------------------------------------------------#
# Random stuff
##########################################################################################################

misc {
    # Set to false to disable all world gen [default: true]
    B:doWorldGen=true
}


##########################################################################################################
# modules
#--------------------------------------------------------------------------------------------------------#
# Individual Modules
##########################################################################################################

modules {
    # Disable to remove this module [default: true]
    B:amber=true

    # Disable to remove this module [default: true]
    B:amethyst=true

    # Disable to remove this module [default: true]
    B:braunite=true

    # Disable to remove this module [default: true]
    B:cinnibar=true

    # Disable to remove this module [default: true]
    B:cobalt=true

    # Disable to remove this module [default: true]
    B:copper=true

    # Disable to remove this module [default: true]
    B:emerald=true

    # Enable to see some WIP stuff [default: false]
    B:fossil=false

    # Disable to remove this module [default: true]
    B:jade=true

    # Disable to remove this module [default: true]
    B:lapis=true

    # Disable to remove this module [default: true]
    B:lead=true

    # Disable to remove this module [default: true]
    B:luminite=true

    # Disable to remove this module [default: true]
    B:meteorite=true

    # Disable to remove this module [default: true]
    B:mythrill=true

    # Disable to remove this module [default: true]
    B:nickel=true

    # Disable to remove this module [default: true]
    B:opal=true

    # Disable to remove this module [default: true]
    B:osmium=true

    # Disable to remove this module [default: true]
    B:platinum=true

    # Disable to remove this module [default: true]
    B:prismarine=true

    # Disable to remove this module [default: true]
    B:ruby=true

    # Disable to remove this module [default: true]
    B:saphire=true

    # Disable to remove this module [default: true]
    B:shulker=true

    # Disable to remove this module [default: true]
    B:silver=true

    # Disable to remove this module [default: true]
    B:steel=true

    # Disable to remove this module [default: true]
    B:tin=true

    # Disable to remove this module [default: true]
    B:titanium=true

    # Disable to remove this module [default: true]
    B:tungsten=true

    # Disable to remove this module [default: true]
    B:uranium=true

    # Disable to remove this module [default: true]
    B:wood=true
}


##########################################################################################################
# ore gen
#--------------------------------------------------------------------------------------------------------#
# Generation of ore
##########################################################################################################

"ore gen" {
    # Choose a number between 1 and 256 to choose the max amethyst height [range: 1 ~ 256, default: 5]
    I:AmethystMax=5

    # Choose a number between 1 and 255 to choose the min amethyst height [range: 1 ~ 255, default: 1]
    I:AmethystMin=1

    # Choose a number between 1 and 100 to change how often you see amethyst [range: 1 ~ 100, default: 2]
    I:AmethystSpawnTries=2

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 64]
    I:amberMax=64

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:amberMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 2]
    I:amberSize=2

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:amberTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 38]
    I:brauniteMax=38

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:brauniteMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 5]
    I:brauniteSize=5

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:brauniteTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 16]
    I:cinnibarMax=16

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:cinnibarMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:cinnibarSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:cinnibarTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 255]
    I:cobaltMax=255

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:cobaltMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 4]
    I:cobaltSize=4

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:cobaltTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 70]
    I:copperMax=70

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:copperMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 8]
    I:copperSize=8

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:copperTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 32]
    I:jadeMax=32

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:jadeMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 4]
    I:jadeSize=4

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:jadeTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 32]
    I:leadMax=32

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:leadMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:leadSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:leadTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 16]
    I:luminiteMax=16

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:luminiteMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:luminiteSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:luminiteTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 16]
    I:mythrillMax=16

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:mythrillMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:mythrillSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:mythrillTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 48]
    I:nickelMax=48

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:nickelMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:nickelSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:nickelTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 48]
    I:opalMax=48

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 32]
    I:opalMin=32

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 5]
    I:opalSize=5

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:opalTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 48]
    I:osmiumMax=48

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:osmiumMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 5]
    I:osmiumSize=5

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:osmiumTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 8]
    I:platinumMax=8

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:platinumMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 1]
    I:platinumSize=1

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:platinumTries=1

    # Choose a number between 1 and 256 to choose the max ruby ore height [range: 1 ~ 256, default: 15]
    I:rubyMax=15

    # Choose a number between 1 and 255 to choose the min ruby ore height [range: 1 ~ 255, default: 1]
    I:rubyMin=1

    # Choose a number between 1 and 100 to change how often you see ruby ore [range: 1 ~ 100, default: 2]
    I:rubySpawnTries=2

    # Choose a number between 1 and 1000 to change the size of ruby ore veins [range: 1 ~ 1000, default: 2]
    I:rubyVeinSize=2

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 16]
    I:saphireMax=16

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:saphireMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 2]
    I:saphireSize=2

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:saphireTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 32]
    I:silverMax=32

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:silverMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 2]
    I:silverSize=2

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:silverTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 48]
    I:tinMax=48

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:tinMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 4]
    I:tinSize=4

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:tinTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 24]
    I:titaniumMax=24

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:titaniumMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 3]
    I:titaniumSize=3

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:titaniumTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 1]
    I:tungstenMax=1

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:tungstenMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 16]
    I:tungstenSize=16

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:tungstenTries=1

    # Choose a number between 1 and 255 to choose the max ore height [range: 1 ~ 255, default: 3]
    I:uraniumMax=3

    # Choose a number between 1 and 255 to choose the min ore height [range: 1 ~ 255, default: 1]
    I:uraniumMin=1

    # Choose a number between 1 and 255 to choose the size of the vein [range: 1 ~ 255, default: 16]
    I:uraniumSize=16

    # Choose a number between 1 and 255 to choose the amount of times the ore tries to spawn [range: 1 ~ 255, default: 1]
    I:uraniumTries=1
}

**Comment by NicosaurusRex99** [comment] 2018-06-25 10:18
Finally reproduced

**Comment by NicosaurusRex99** [comment] 2018-06-25 10:27
in order to fix this i am going to have to remove the vein size config option (reset your config file in the next update)

**Comment by NicosaurusRex99** [comment] 2018-06-27 16:26
Fixed in 6f95c92

**Closed as completed by NicosaurusRex99** 2018-06-27 16:26 UTC
